name: doanmonhoc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  provider: ^6.0.5
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/lap1.png
    - images/lap12.png
    - images/lap13.png
    - images/lap14.png
    - images/lap15.png
    - images/lap16.png
    - images/a1.png
    - images/a2.png
    - images/a3.png
    - images/login.jpg
    - images/signup.jpg
    - images/NK.png
    - images/brands/
    - images/laptops/
    - images/forgot_password.jpg